version: '3.9'

x-maxscale-environment: &maxscale-environment
  MARIADB_MASTER_HOST: ${DB_MASTER_HOST:-db-master}

x-maxscale-users-environment: &maxscale-users-environment
  MARIADB_MONITOR_USER: ${DB_MONITOR_USER:-monitoring}
  MARIADB_MONITOR_PASSWORD: ${DB_MONITOR_PASSWORD:-monitoring}
  MARIADB_MAXSCALE_USER: ${DB_MAXSCALE_USER:-maxscale}
  MARIADB_MAXSCALE_PASSWORD: ${DB_MAXSCALE_PASSWORD:-maxscale}

x-mariadb-service: &mariadb-service
  image: digilabs/mariadb:10.11.5
  build:
    context: .
    dockerfile: .docker/mariadb/Dockerfile
  environment: &mariadb-environment
    <<: *maxscale-users-environment
    MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-digilabs}
    MARIADB_INITDB_SKIP_TZINFO: 'Y'
    MARIADB_REPLICATION_USER: ${DB_REPLICATION_USER:-replication}
    MARIADB_REPLICATION_PASSWORD: ${DB_REPLICATION_PASSWORD:-replication}
  restart: always
  networks:
    - mariadb_maxscale

services:
  db-proxy:
    image: digilabs/mariadb/maxscale:24.02
    build:
      context: .
      dockerfile: .docker/maxscale/Dockerfile
    container_name: db-proxy
    restart: always
    environment:
      <<: [*maxscale-environment, *maxscale-users-environment]
      MARIADB_SLAVE_HOST: ${DB_SLAVE_HOST:-db-slave}
    ports:
      - "8989:8989"
      - "${DB_PORT:-3306}:3306"
    depends_on:
      - db-master
      - db-slave
    networks:
      - mariadb_maxscale
  
  db-master:
    <<: *mariadb-service
    command:
      - '--server_id=1'
      - '--log-bin'
      - '--log-basename=my-mariadb'
    container_name: db-master
    environment:
      <<: *mariadb-environment
      MARIADB_USER: ${DB_USER:-digilabs}
      MARIADB_PASSWORD: ${DB_PASSWORD:-digilabs}
      MARIADB_DATABASE: ${DB_DATABASE:-digilabs}
    volumes:
      - db_data:/var/lib/mysql

  db-slave:
    <<: *mariadb-service
    container_name: db-slave
    command:
      - '--server_id=2'
      - '--read_only=1'
      - '--log-basename=my-mariadb'
    environment:
      <<: [*mariadb-environment, *maxscale-environment]
    volumes:
      - db_slave_data:/var/lib/mysql
    depends_on:
      - db-master

volumes:
  db_data:
  db_slave_data:

networks:
  mariadb_maxscale:
    driver: bridge